<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Yourmodname\Module'                        => __DIR__ . '/Module.php',
    'Yourmodname\Controller\IndexController' => __DIR__ . '/src/Yourmodname/Controller/IndexController.php',
    'YourmodnameTest\Framework\TestCase'        => __DIR__ . '/tests/Yourmodname/Framework/TestCase.php',
    'YourmodnameTest\SampleTest'                => __DIR__ . '/tests/Yourmodname/SampleTest.php',
);
